package util

import (
	"bytes"
	"strings"

	"golang.org/x/net/html"
)

// SanitizeHTML removes dangerous HTML elements and attributes from rendered
// markdown output to prevent XSS attacks. Safe HTML tags generated by the
// markdown parser (<p>, <a>, <img>, <code>, <strong>, etc.) are preserved,
// while <script>, <iframe>, event handlers (on*), javascript: URLs, etc.
// are stripped.
func SanitizeHTML(input string) string {
	doc, err := html.Parse(strings.NewReader(input))
	if err != nil {
		return input
	}

	// Walk the tree and remove dangerous nodes (bottom-up so sibling pointers stay valid)
	var sanitize func(*html.Node)
	sanitize = func(n *html.Node) {
		if n == nil {
			return
		}

		// Process children first — capture next before recursion since the child may be removed
		for c := n.FirstChild; c != nil; {
			next := c.NextSibling
			sanitize(c)
			c = next
		}

		if n.Type == html.ElementNode {
			tag := strings.ToLower(n.Data)

			// Remove dangerous elements entirely (including their children)
			switch tag {
			case "script", "iframe", "object", "embed", "applet",
				"frame", "frameset", "form", "input", "textarea",
				"select", "button", "style", "link", "meta", "base":
				if n.Parent != nil {
					n.Parent.RemoveChild(n)
				}
				return
			}

			// Filter dangerous attributes
			var safeAttrs []html.Attribute
			for _, a := range n.Attr {
				key := strings.ToLower(a.Key)
				val := a.Val
				valLower := strings.ToLower(val)

				// Remove event handlers (onclick, onload, onerror, etc.)
				if strings.HasPrefix(key, "on") {
					continue
				}

				// Remove javascript: and data: URLs in src/href/action/xlink:href
				if key == "href" || key == "src" || key == "action" || key == "xlink:href" {
					if strings.HasPrefix(valLower, "javascript:") ||
						strings.HasPrefix(valLower, "data:") {
						continue
					}
				}

				safeAttrs = append(safeAttrs, a)
			}
			n.Attr = safeAttrs
		}

		// Strip raw text that looks like a script injection inside otherwise-safe elements
		if n.Type == html.TextNode {
			// Text nodes are safe as-is — the browser won't interpret them as tags
		}
	}

	sanitize(doc)

	// Extract only the <body> children — html.Parse wraps content in <html><head><body>
	var body *html.Node
	var findBody func(*html.Node)
	findBody = func(n *html.Node) {
		if n.Type == html.ElementNode && strings.ToLower(n.Data) == "body" {
			body = n
			return
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			findBody(c)
		}
	}
	findBody(doc)

	if body == nil {
		// Fallback: render the full parsed document
		var buf bytes.Buffer
		if err := html.Render(&buf, doc); err != nil {
			return input
		}
		return buf.String()
	}

	var buf bytes.Buffer
	for c := body.FirstChild; c != nil; c = c.NextSibling {
		if err := html.Render(&buf, c); err != nil {
			return input
		}
	}
	return buf.String()
}
