package util

import (
	"bytes"
	"strings"

	"golang.org/x/net/html"
)

// controlChars removes ASCII tab/newline/carriage-return so that URL checks
// like "java\nscript:" cannot slip past the prefix match (browsers strip
// these characters during URL parsing).
var controlChars = strings.NewReplacer("\t", "", "\n", "", "\r", "")

// SanitizeHTML removes dangerous HTML elements and attributes from rendered
// markdown output to prevent XSS attacks. Safe HTML tags generated by the
// markdown parser (<p>, <a>, <img>, <code>, <strong>, etc.) are preserved,
// while <script>, event handlers (on*), javascript: URLs, srcdoc, etc.
// are stripped.
//
// 正文是作者本人撰写的内容，据此按“可信作者”模型处理：不再对嵌入标签
// （iframe/embed/object）的 src/data 做 scheme 白名单限制，//host/path、
// /path、file: 等地址一律保留，能加载什么交给浏览器决定。放行范围仅限
// 地址本身，<script>/on*/srcdoc/javascript:/非图片 data: 仍然一律剥除。
func SanitizeHTML(input string) string {
	doc, err := html.Parse(strings.NewReader(input))
	if err != nil {
		return input
	}

	// Walk the tree and remove dangerous nodes (bottom-up so sibling pointers stay valid)
	var sanitize func(*html.Node)
	sanitize = func(n *html.Node) {
		if n == nil {
			return
		}

		// Process children first — capture next before recursion since the child may be removed
		for c := n.FirstChild; c != nil; {
			next := c.NextSibling
			sanitize(c)
			c = next
		}

		if n.Type == html.ElementNode {
			tag := strings.ToLower(n.Data)

			// Remove dangerous elements entirely (including their children).
			// 正文由作者本人撰写，其中的 iframe/embed/object 等嵌入标签属于
			// 可信内容，其 src/data 不再做 scheme 白名单限制（//host/path、
			// /path、file: 等一律照原样渲染，能加载什么由浏览器决定）。
			// 真正的兜底是上面这条危险元素删除，加上下面的 javascript:/data:
			// 通用拦截与 srcdoc/on* 剥除。
			switch tag {
			case "script", "applet", "frame", "frameset", "form", "input",
				"textarea", "select", "button", "style", "link", "meta",
				"base", "svg", "math":
				if n.Parent != nil {
					n.Parent.RemoveChild(n)
				}
				return
			}

			// Filter dangerous attributes
			var safeAttrs []html.Attribute
			for _, a := range n.Attr {
				key := strings.ToLower(a.Key)
				val := a.Val
				valLower := strings.ToLower(controlChars.Replace(val))

				// Remove event handlers (onclick, onload, onerror, etc.)
				if strings.HasPrefix(key, "on") {
					continue
				}

				// srcdoc 让 iframe 内嵌任意 HTML 并继承父页面源（同源），
				// 等同 XSS，一律剥除。
				if key == "srcdoc" {
					continue
				}

				// Remove javascript: and non-image data: URLs in src/href/action/xlink:href
				// 前导空白一并忽略，避免 "  javascript:" 之类写法绕过前缀匹配。
				if key == "href" || key == "src" || key == "action" || key == "xlink:href" || key == "data" {
					schemeVal := strings.TrimSpace(valLower)
					if strings.HasPrefix(schemeVal, "javascript:") {
						continue
					}
					if strings.HasPrefix(schemeVal, "data:") && !strings.HasPrefix(schemeVal, "data:image/") {
						continue
					}
				}

				safeAttrs = append(safeAttrs, a)
			}
			n.Attr = safeAttrs
		}

		// Strip raw text that looks like a script injection inside otherwise-safe elements
		if n.Type == html.TextNode {
			// Text nodes are safe as-is — the browser won't interpret them as tags
		}
	}

	sanitize(doc)

	// Extract only the <body> children — html.Parse wraps content in <html><head><body>
	var body *html.Node
	var findBody func(*html.Node)
	findBody = func(n *html.Node) {
		if n.Type == html.ElementNode && strings.ToLower(n.Data) == "body" {
			body = n
			return
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			findBody(c)
		}
	}
	findBody(doc)

	if body == nil {
		// Fallback: render the full parsed document
		var buf bytes.Buffer
		if err := html.Render(&buf, doc); err != nil {
			return input
		}
		return buf.String()
	}

	var buf bytes.Buffer
	for c := body.FirstChild; c != nil; c = c.NextSibling {
		if err := html.Render(&buf, c); err != nil {
			return input
		}
	}
	return buf.String()
}
